// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOkpMUI_pTHtnMPByXWDYCFh3aaeaSaTY',
    appId: '1:679621760186:web:0ae380c6ab80472611de83',
    messagingSenderId: '679621760186',
    projectId: 'zvuki-ede81',
    authDomain: 'zvuki-ede81.firebaseapp.com',
    storageBucket: 'zvuki-ede81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCezj7r1byGJjqKIVMzmwVHDT9ErxnnS30',
    appId: '1:679621760186:android:d6a5f8c2839711a511de83',
    messagingSenderId: '679621760186',
    projectId: 'zvuki-ede81',
    storageBucket: 'zvuki-ede81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZs1c8QONUbvWz8wArY0GeauooJaiA9ns',
    appId: '1:679621760186:ios:e87bfd6f7a67ae3111de83',
    messagingSenderId: '679621760186',
    projectId: 'zvuki-ede81',
    storageBucket: 'zvuki-ede81.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZs1c8QONUbvWz8wArY0GeauooJaiA9ns',
    appId: '1:679621760186:ios:e87bfd6f7a67ae3111de83',
    messagingSenderId: '679621760186',
    projectId: 'zvuki-ede81',
    storageBucket: 'zvuki-ede81.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOkpMUI_pTHtnMPByXWDYCFh3aaeaSaTY',
    appId: '1:679621760186:web:0b5b75e282ec161d11de83',
    messagingSenderId: '679621760186',
    projectId: 'zvuki-ede81',
    authDomain: 'zvuki-ede81.firebaseapp.com',
    storageBucket: 'zvuki-ede81.firebasestorage.app',
  );
}
